PREFIX :       <http://example/>
PREFIX rdfstar: <https://w3id.org/rdfstar/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT * {

    [a rdfstar:QutotedStatement;
      rdf:subject :a ;
      rdf:predicate :b ;
      rdf:object :c ; ] ?p ?o .


}
